# Generated by cmake/regen_tests.py - do not edit by hand.
# Source lists mirror the automake check_PROGRAMS / *_SOURCES variables.

gsl_add_test(block test
    block/test.c
)

gsl_add_test(bspline test
    bspline/test.c
)

gsl_add_test(bst test
    bst/test.c
)

gsl_add_test(cblas test
    cblas/test.c
    cblas/test_amax.c
    cblas/test_asum.c
    cblas/test_axpy.c
    cblas/test_copy.c
    cblas/test_dot.c
    cblas/test_gbmv.c
    cblas/test_gemm.c
    cblas/test_gemm_loops.c
    cblas/test_gemv.c
    cblas/test_ger.c
    cblas/test_hbmv.c
    cblas/test_hemm.c
    cblas/test_hemv.c
    cblas/test_her.c
    cblas/test_her2.c
    cblas/test_her2k.c
    cblas/test_herk.c
    cblas/test_hpmv.c
    cblas/test_hpr.c
    cblas/test_hpr2.c
    cblas/test_nrm2.c
    cblas/test_rot.c
    cblas/test_rotg.c
    cblas/test_rotm.c
    cblas/test_rotmg.c
    cblas/test_sbmv.c
    cblas/test_scal.c
    cblas/test_spmv.c
    cblas/test_spr.c
    cblas/test_spr2.c
    cblas/test_swap.c
    cblas/test_symm.c
    cblas/test_symv.c
    cblas/test_syr.c
    cblas/test_syr2.c
    cblas/test_syr2k.c
    cblas/test_syrk.c
    cblas/test_tbmv.c
    cblas/test_tbsv.c
    cblas/test_tpmv.c
    cblas/test_tpsv.c
    cblas/test_trmm.c
    cblas/test_trmv.c
    cblas/test_trsm.c
    cblas/test_trsv.c
)

gsl_add_test(cdf test
    cdf/test.c
)

gsl_add_test(cheb test
    cheb/test.c
)

gsl_add_test(combination test
    combination/test.c
)

gsl_add_test(complex test
    complex/test.c
)

gsl_add_test(const test
    const/test.c
)

gsl_add_test(deriv test
    deriv/test.c
)

gsl_add_test(dht test
    dht/test.c
)

gsl_add_test(diff test
    diff/test.c
)

gsl_add_test(eigen test
    eigen/test.c
)

gsl_add_test(err test
    err/test.c
)

gsl_add_test(fft test
    fft/test.c
    fft/signals.c
)

gsl_add_test(filter test
    filter/test.c
)

gsl_add_test(fit test
    fit/test.c
)

gsl_add_test(histogram test
    histogram/test.c
    histogram/test1d.c
    histogram/test2d.c
    histogram/test1d_resample.c
    histogram/test2d_resample.c
    histogram/test1d_trap.c
    histogram/test2d_trap.c
)

gsl_add_test(ieee-utils test
    ieee-utils/test.c
)

gsl_add_test(integration test
    integration/test.c
    integration/tests.c
)

gsl_add_test(interpolation test
    interpolation/test.c
)

gsl_add_test(linalg test
    linalg/test.c
)

gsl_add_test(matrix test
    matrix/test.c
)

gsl_add_test(matrix test_static
    matrix/test_static.c
)

gsl_add_test(min test
    min/test.c
    min/test_funcs.c
)

gsl_add_test(monte test
    monte/test.c
)

gsl_add_test(movstat test
    movstat/test.c
)

gsl_add_test(multifit test
    multifit/test.c
)

gsl_add_test(multifit_nlinear test
    multifit_nlinear/test.c
)

gsl_add_test(multilarge test
    multilarge/test.c
)

gsl_add_test(multilarge_nlinear test
    multilarge_nlinear/test.c
)

gsl_add_test(multimin test
    multimin/test.c
    multimin/test_funcs.c
)

gsl_add_test(multiroots test
    multiroots/test.c
    multiroots/test_funcs.c
)

gsl_add_test(multiset test
    multiset/test.c
)

gsl_add_test(ntuple test
    ntuple/test.c
)

gsl_add_test(ode-initval test
    ode-initval/test.c
)

gsl_add_test(ode-initval2 test
    ode-initval2/test.c
)

gsl_add_test(permutation test
    permutation/test.c
)

gsl_add_test(poly test
    poly/test.c
)

gsl_add_test(qrng test
    qrng/test.c
)

gsl_add_test(randist test
    randist/test.c
)

gsl_add_test(rng test
    rng/test.c
)

gsl_add_test(roots test
    roots/test.c
    roots/test_funcs.c
)

gsl_add_test(rstat test
    rstat/test.c
)

gsl_add_test(siman test
    siman/test.c
)

gsl_add_test(sort test
    sort/test.c
)

gsl_add_test(spblas test
    spblas/test.c
)

gsl_add_test(specfunc test
    specfunc/test_sf.c
    specfunc/test_airy.c
    specfunc/test_alf.c
    specfunc/test_bessel.c
    specfunc/test_coulomb.c
    specfunc/test_dilog.c
    specfunc/test_gamma.c
    specfunc/test_hermite.c
    specfunc/test_hyperg.c
    specfunc/test_legendre.c
    specfunc/test_mathieu.c
    specfunc/test_sincos_pi.c
)

gsl_add_test(splinalg test
    splinalg/test.c
)

gsl_add_test(spmatrix test
    spmatrix/test.c
)

gsl_add_test(statistics test
    statistics/test.c
    statistics/test_nist.c
    statistics/test_robust.c
)

gsl_add_test(sum test
    sum/test.c
)

gsl_add_test(sys test
    sys/test.c
)

gsl_add_test(vector test
    vector/test.c
)

gsl_add_test(vector test_static
    vector/test_static.c
)

gsl_add_test(wavelet test
    wavelet/test.c
)
