#!/usr/bin/env python3
"""Regenerate cmake/gsl_sources.cmake from the per-module Makefile.am files.

GSL keeps its authoritative source lists in automake's ``*_la_SOURCES``
variables.  The CMake build uses a checked-in explicit list; this script
derives that list so it cannot silently drift from automake.

Usage (from anywhere):  python cmake/regen_sources.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cmake", "gsl_sources.cmake")

# Directories whose Makefile.am contribute to one of the two libraries.
SKIP_DIRS = {"gsl", "doc", "doc_texinfo", "build.vc", "scripts", ".git"}

SOURCES_RE = re.compile(r"^\s*(\S+)_la_SOURCES\s*=\s*(.*)$")


def logical_lines(text):
    """Yield Makefile lines with backslash continuations joined."""
    buf = ""
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.endswith("\\"):
            buf += line[:-1] + " "
            continue
        buf += line
        yield buf
        buf = ""
    if buf.strip():
        yield buf


def collect_sources(makefile):
    """Return the .c files listed in all *_la_SOURCES variables."""
    result = []
    with open(makefile, "r", encoding="utf-8", errors="replace") as fh:
        for line in logical_lines(fh.read()):
            m = SOURCES_RE.match(line)
            if not m:
                continue
            for token in m.group(2).split():
                if token.endswith(".c"):
                    result.append(token)
    return result


def find_modules():
    modules = []
    for name in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, name)
        if not os.path.isdir(path) or name in SKIP_DIRS or name.startswith("."):
            continue
        if os.path.isfile(os.path.join(path, "Makefile.am")):
            modules.append(name)
    return modules


def repo_relative(path):
    return path.replace(os.sep, "/")


def main():
    if not os.path.isfile(os.path.join(ROOT, "gsl_math.h")):
        sys.exit("error: %s does not look like the GSL source root" % ROOT)

    gsl = ["version.c"]
    cblas = []

    for module in find_modules():
        makefile = os.path.join(ROOT, module, "Makefile.am")
        srcs = collect_sources(makefile)
        if not srcs:
            continue
        if module == "cblas":
            cblas = [repo_relative(os.path.join(module, s)) for s in srcs]
        else:
            for s in srcs:
                gsl.append(repo_relative(os.path.join(module, s)))

    if not cblas:
        sys.exit("error: no CBLAS sources found")

    lines = [
        "# Generated by cmake/regen_sources.py - do not edit by hand.",
        "# Source lists mirror the automake *_la_SOURCES variables.",
        "",
        "set(GSL_CBLAS_SOURCES",
    ]
    lines += ["    %s" % s for s in cblas]
    lines += [")", "", "set(GSL_SOURCES", "    version.c"]
    lines += ["    %s" % s for s in gsl if s != "version.c"]
    lines += [")", ""]

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("wrote %s (%d gsl sources, %d cblas sources)"
          % (repo_relative(OUT), len(gsl), len(cblas)))


if __name__ == "__main__":
    main()
