#!/usr/bin/env python3
"""Regenerate cmake/gsl_tests.cmake from the per-module Makefile.am files.

Emits one ``gsl_add_test(<module> <name> <sources...>)`` call per
``check_PROGRAMS`` entry.  Programs whose source list is not fully explicit
(uses a make variable such as ``$(test_SOURCES)``) are skipped; the module's
plain ``test`` program still covers them.

Usage (from anywhere):  python cmake/regen_tests.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cmake", "gsl_tests.cmake")

SKIP_DIRS = {"gsl", "doc", "doc_texinfo", "build.vc", "scripts", ".git"}

PROGRAMS_RE = re.compile(r"^\s*check_PROGRAMS\s*=\s*(.*)$")
SOURCES_RE = re.compile(r"^\s*(\S+)_SOURCES\s*=\s*(.*)$")


def logical_lines(text):
    buf = ""
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.endswith("\\"):
            buf += line[:-1] + " "
            continue
        buf += line
        yield buf
        buf = ""
    if buf.strip():
        yield buf


def strip_comment(line):
    idx = line.find("#")
    return line if idx < 0 else line[:idx]


def parse_module(makefile):
    programs = []
    sources = {}
    with open(makefile, "r", encoding="utf-8", errors="replace") as fh:
        for line in logical_lines(fh.read()):
            line = strip_comment(line)
            m = PROGRAMS_RE.match(line)
            if m:
                programs += m.group(1).split()
                continue
            m = SOURCES_RE.match(line)
            if m:
                sources[m.group(1)] = m.group(2).split()
    return programs, sources


def collect():
    entries = []
    for module in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, module)
        if not os.path.isdir(path) or module in SKIP_DIRS or module.startswith("."):
            continue
        makefile = os.path.join(path, "Makefile.am")
        if not os.path.isfile(makefile):
            continue
        programs, sources = parse_module(makefile)
        for program in programs:
            tokens = sources.get(program, [])
            if any("$(" in t for t in tokens):
                continue
            files = [t for t in tokens if t.endswith(".c")]
            if not files:
                continue
            files = ["%s/%s" % (module, f) for f in files]
            entries.append((module, program, files))
    return entries


def main():
    if not os.path.isfile(os.path.join(ROOT, "gsl_math.h")):
        sys.exit("error: %s does not look like the GSL source root" % ROOT)

    entries = collect()

    lines = [
        "# Generated by cmake/regen_tests.py - do not edit by hand.",
        "# Source lists mirror the automake check_PROGRAMS / *_SOURCES variables.",
        "",
    ]
    for module, program, files in entries:
        lines.append("gsl_add_test(%s %s" % (module, program))
        lines += ["    %s" % f for f in files]
        lines.append(")")
        lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("wrote %s (%d test programs)"
          % (os.path.relpath(OUT, ROOT).replace(os.sep, "/"), len(entries)))


if __name__ == "__main__":
    main()
